In [1]:
# 사이킷런 모듈 import
import sklearn

In [2]:
# 사이킷런에서 제공하는 아이리스 데이터 세트 로딩
from sklearn.datasets import load_iris

In [3]:
# train 데이터와 test 데이터를 분리해줄 함수사용을 위해 train_test_split함수 를
# 사용가능하게 하는 모듈을 임포트 합니다
from sklearn.model_selection import train_test_split

In [4]:
# 판다스 모듈 로딩
import pandas as pd
# 붓꽃 데이터 세트 로딩
iris = load_iris()

In [5]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
print(type(iris.data))
print(iris.data.shape)
# iris.data 를 앞으로 feature 라고 부를 예정입니다.

<class 'numpy.ndarray'>
(150, 4)


In [12]:
# tartet : 150개의 품종 결정값들
iris.target
# target 이라는 단어 대신 결정값 또는 라벨 이라는 단어를 섞어서 쓰기도 합니다

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
# feature(data) 들의 각 항목(열)의 제목들
print(iris.feature_names)
# target_names : target 값을이 나타내는 이름들
print(iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [16]:
# 위 내용을 한번에 확인
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [58]:
# 위 데이터 들을 대상으로 머신러닝 모델을 만들기 위해서는
# feature_names 와 target_names 를 컬럼이름들로 구성하고, 그 값으로 data 와
# target 들로 구성된 하나의 데이터프레임이 필요합니다
# iris 데이터를 대상으로 데이터 프레임을 제작합니다

# data 와 target 을 별도의 변수로 저장하여 분리합니다
iris_data = iris.data
iris_label = iris.target

In [59]:
# feature_names 으로 컬럼 이름설정하고, data 를 iris_data로 하여 데이터 프레임을
# 생성합니다
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

In [60]:
# 새롭게 생성된 데이터 프레임에 lable 이라는 컬럼을 생성하고 그 값들로
#  iris_label 값들을 대입합니다
iris_df['label'] = iris_label

In [61]:
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [62]:
# 학습데이터와 테스트데어터로 분리
# X_train : 학습용 피쳐, 
# X_test : 테스트용 피쳐
# y_train : 학습용 타겟
# y_test : 테스트용 타겟
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, 
                                                test_size=0.2, random_state=11)
# X_train 과 y_train 으로 학습
# X_text 예측 y_train 으로 결과비교

# iris_data : 전체 feature
# iris_label : 전체 target
# test_size=0.2 : 테스트 데이터의 수량 비율. 현재 전체 데이터가 150 건이므로 
# 테스트 데이터는 30건으로 분리됨.
# random_state : 랜덤 시드 값. 랜덤하게 골라진 데이터로 분리 되는데 관여하는 
# 임의 설정값

In [63]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [64]:
# 머신러닝의 알고림즘 중 결정트리(DecisionTree) 알고리즘을 선택 사용합니다
from sklearn.tree import DecisionTreeClassifier

In [65]:
# X_train 데이터와 y_train  타겟이 연결되어 학습
# 학습된 모델에 X_test  데이터를 적용하여 나오는 결과를 예측값이라고 합니다.
# 예측값과 y_test 값들을 비교해서 성능을 평가합니다

# DecisionTreeClassifier 객체 생성 
dt_clf = DecisionTreeClassifier(random_state=11)
# 학습데이터로 학습을 수행(fit)
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [66]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트(X_test)로 
# 예측 수행. (predict)
pred = dt_clf.predict(X_test)

In [67]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [68]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [69]:
k = 0

for i in pred:
    if i == 0 :
        result = 'setosa'
        print(X_test[k], " : " , result)
    elif i == 1 :
        result = 'versicolor'
        print(X_test[k], " : " , result)
    else : 
        result = 'virginica'
        print(X_test[k], " : " , result)
    k = k + 1

[6.8 3.  5.5 2.1]  :  virginica
[6.7 3.  5.2 2.3]  :  virginica
[6.3 2.8 5.1 1.5]  :  versicolor
[6.3 3.3 4.7 1.6]  :  versicolor
[6.4 2.7 5.3 1.9]  :  virginica
[4.9 3.1 1.5 0.1]  :  setosa
[6.7 3.1 4.4 1.4]  :  versicolor
[5.7 4.4 1.5 0.4]  :  setosa
[4.8 3.1 1.6 0.2]  :  setosa
[6.1 2.9 4.7 1.4]  :  versicolor
[6.  2.2 5.  1.5]  :  versicolor
[6.  2.2 4.  1. ]  :  versicolor
[5.4 3.  4.5 1.5]  :  versicolor
[5.7 2.5 5.  2. ]  :  virginica
[6.9 3.1 5.4 2.1]  :  virginica
[4.5 2.3 1.3 0.3]  :  setosa
[6.3 2.9 5.6 1.8]  :  virginica
[5.6 3.  4.5 1.5]  :  versicolor
[6.5 3.2 5.1 2. ]  :  virginica
[5.8 2.7 5.1 1.9]  :  virginica
[5.6 2.5 3.9 1.1]  :  versicolor
[4.7 3.2 1.3 0.2]  :  setosa
[4.6 3.6 1.  0.2]  :  setosa
[6.4 3.2 4.5 1.5]  :  versicolor
[4.8 3.  1.4 0.1]  :  setosa
[4.8 3.4 1.6 0.2]  :  setosa
[5.9 3.  5.1 1.8]  :  virginica
[6.6 3.  4.4 1.4]  :  versicolor
[5.4 3.9 1.3 0.4]  :  setosa
[6.  3.4 4.5 1.6]  :  versicolor


**예측 정확도 평가**

In [70]:
from sklearn.metrics import accuracy_score
# 실제 타겟과  predict(테스트 피쳐) 결과값을 비교
result = accuracy_score(y_test, pred)
print('예측 정확도: {0:.4f}'.format(result))

예측 정확도: 0.9333


In [71]:
import numpy as np
pred = dt_clf.predict(np.array([[4,4,5,5]]))

In [72]:
for i in pred:
    if i == 0 :
        result = 'setosa'
    elif i == 1 :
        result = 'versicolor'
    else : 
        result = 'virginica'
    print('[4,4,5,5] : ' , result)
    k = k + 1

[4,4,5,5] :  virginica
