In [1]:
import cv2
import numpy as np

In [2]:
def readImg():
    imgage = cv2.imread("./image/20200526.png")
    return imgage
def showImg(imgage):
    cv2.imshow("shinchon20200526", imgage)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
img = readImg()
showImg(img)

In [3]:
(height, width) = img.shape[:2]
center = (width // 2, height // 2)

In [7]:
# 원본 이미지와 가로 세로 비율이 똑같고, 모두 0으로 체워진 배열(이미지) 생성
mask = np.zeros(img.shape[:2], dtype = "uint8")
print(mask.shape)
print(mask)
showImg(mask)

(600, 600)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
# 중점 좌표 center , 반지름 300짜리 원을 흰색으로 채워서 mask 이미지에 그림
cv2.circle(mask, center, 300, (255, 255, 255), -1)
print(mask)
print(mask[1])
showImg(mask)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0

In [14]:
# img 와 mask 이미지를 mask 방식으로 합칩니다(and 연산 : 둘다 1 이면 1, 나머지는 0 )
# mask 이미지의 원 내분는 모두 1, 나머지는 0 이므로 
# 원내부에서 합쳐지는  img 이미지가 표시되고 
# 이미 모두 0 인 mask 의 원의 외부 영역은 img 이미지 에  무엇이 있든 모두 0으로 계산
masked = cv2.bitwise_and(img, img, mask = mask)
showImg(masked)

In [15]:
# 11111111 and 10100011  -> 10100011
# 0과 and 연산된 A -> 0
# 1과 and 연산된 A -> A