In [3]:
import cv2
import numpy as np

In [4]:
def readImg():
    imgage = cv2.imread("./image/20200526.png")
    return imgage
def showImg(imgage):
    cv2.imshow("shinchon20200526", imgage)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
img = readImg()
showImg(img)

In [5]:
(height, width) = img.shape[:2]
center = (width // 2, height // 2)

In [6]:
# 각 채널별 이미지를 분리
(Blue, Green, Red) = cv2.split(img)

In [15]:
showImg(Blue)

In [10]:
showImg(Green)

In [11]:
showImg(Red)

In [14]:
print(Blue)   #(XX,YY, Blue)

[[ 27  27  27 ...  80  77  82]
 [ 27  27  27 ...  82  81  81]
 [ 27  27  27 ...  82  83  79]
 ...
 [ 85  86  87 ... 141 138 137]
 [103 108 107 ... 140 138 137]
 [102 104 101 ... 144 142 141]]


In [9]:
zeros = np.zeros(img.shape[:2], dtype = "uint8")
RedImg = cv2.merge([zeros, zeros, Red])
showImg(RedImg)

In [10]:
# GRAY, HSV모드로의 이미지 변환 결과
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
showImg(gray)

In [11]:
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
showImg(hsv)

In [12]:
lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
showImg(lab)

In [13]:
# 그림의 채널병합
BGR = cv2.merge([Blue, Green, Red])
showImg(BGR)