In [21]:
import cv2
import numpy as np
img = cv2.imread("./image/marathon_01.jpg")
(height, width) = img.shape[:2]

In [22]:
# 얼굴인식 모델이 있는 경로와 파일 이름을 저장
face_cascade_name = './data/haarcascade_frontalface_alt.xml'
eyes_cascade_name = './data/haarcascade_eye_tree_eyeglasses.xml'

In [23]:
# 얼굴과 눈 분류 모델 객체 생성
face_cascade = cv2.CascadeClassifier()
eyes_cascade = cv2.CascadeClassifier()

In [24]:
# 식별 객체 로딩을 테스트하여 실패하였을 경우 메세지 전송하고 프로그램 종료
if not face_cascade.load(cv2.samples.findFile(face_cascade_name)):
    print('--(!)Error loading face cascade')
    exit(0)
if not eyes_cascade.load(cv2.samples.findFile(eyes_cascade_name)):
    print('--(!)Error loading eyes cascade')
    exit(0)

In [25]:
def showImg(imgage):
    cv2.imshow("Face Detect", imgage)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [26]:
showImg(img)

In [27]:
# 그레이 스케일로 변환
frame_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
showImg(frame_gray)

In [28]:
# 색상 간격(채도 수치 간격)을 넓혀줍니다
frame_gray = cv2.equalizeHist(frame_gray)
showImg(frame_gray)

In [29]:
# 얼굴인식 실행( 결과 : 인식된 얼굴의 좌표들의 리스트)
faces = face_cascade.detectMultiScale(frame_gray)
print(faces)
# [[ 82  41 106 106]]  : x좌표 , y좌표, 가로길이, 세로길이

[[586 226  49  49]
 [689 210  57  57]
 [464 218  52  52]
 [660 309  59  59]
 [309 192  54  54]
 [822 223  63  63]
 [252 255  61  61]
 [ 28 238  56  56]
 [406 257  57  57]
 [949 272  55  55]
 [113 275  63  63]]


In [30]:
faces.shape

(11, 4)

In [31]:
def detectAndDisplay(frame):
    for (x,y,w,h) in faces:
        # 인식된 얼굴 영역을 하나씩 반복 실행문에서 전달받아 사각형을 그립니다
        frame = cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        # frame_gray 에서 인식한 얼굴의 좌표와 크기로 img 에 사각형을 그립니다

        # 현재 얼굴의 픽셀 영역을 faceROI 에 저장
        faceROI = frame_gray[y:y+h,x:x+w]  

        # faceROI 영역을 대상으로 눈(안구)인식 실행
        eyes = eyes_cascade.detectMultiScale(faceROI)

        for (x2,y2,w2,h2) in eyes:
            # 그려넣을 원의 중점계산. 
            # x:얼굴의 x 좌표   x2 : 얼굴 내에서 계산한 눈의 x 좌표, w2 : 눈의 가로크기
            # y:얼굴의 y 좌표   y2 : 얼굴 내에서 계산한 눈의 y 좌표, h2 : 눈의 세로크기
            eye_center = (x + x2 + w2//2, y + y2 + h2//2) 

            # (가로+세로) 의 1/4 로 반지름 계산
            radius = int(round((w2 + h2)*0.25))

            # 계산된 눈의 위치에 원을 그려 넣습니다.
            frame = cv2.circle(frame, eye_center, radius, (255, 255, 0 ), 2)
    showImg(frame)

In [32]:
# 식별 함수 호출
detectAndDisplay(img)